workspace = { members = [ "Rust-Book/common_concepts",
    "Rust-Book/guessing_game",
    "Rust-Book/structure",
    "Rust-Book/understanding-ownership",
    "Rust-Book/enums"] }
[package]
name = "hello_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
